# For details of what checks are run for PRs please refer below
name: .NET CI

on: [pull_request, workflow_dispatch]

jobs:
  # Fail if there are build warnings
  build-warnings:
    name: Build warnings check
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3.3.0
  
      - name: Build
        run: dotnet build /WarnAsError

  test:
    name: Tests for .NET ${{ matrix.framework }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        framework: ['8.0']
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v3.3.0

    - name: Tests
      run: dotnet test --framework netcoreapp${{ matrix.framework }}
